def latch = createLatch count: 2;

def var1 = false;
def var2 = false;

parallel(
        wait: {
            awaitLatch latch
            echo "var1=${var1}"
            echo "var2=${var2}"
        },
        countdown1: {
            sleep 3
            var1 = true
            countDownLatch latch
        },
        countdown2: {
            sleep 2
            var2 = true
            countDownLatch latch
        }
)

