def barrier = createBarrier count: 3;

boolean out = false

parallel(

        await1: {
            awaitBarrier barrier
            echo "out=${out}"
        },
        await2: {
            sleep 2
            awaitBarrier barrier
            echo "out=${out}"
        },
        await3: {
            sleep 3
            out = true
            awaitBarrier barrier
            echo "out=${out}"
        }
)